/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BLL;

import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Maxime
 */
public class Service {

    /**
     * Problem 1
     * If we list all the natural numbers below 10 that are
     * multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of 
     * these multiples is 23.
     * Find the sum of all the multiples of 3 or 5 below 1000.
     */
    public static void problem1_Algo() {
        int sum = 0;
        int[] tab = new int[1000];
        for (int i = 0; i < 1000; i++) {
            if ((i % 3 == 0) || (i % 5 == 0)) {
                sum += i;
            }
        }
        System.out.println("The sum of all these number is : " + sum);
    } 
    /**
     * Problem 2
     * Each new term in the Fibonacci sequence is generated by
     * adding the previous two terms. By starting with 1 and 2,
     * the first 10 terms will be:
     * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...By considering the
     * terms in the Fibonacci sequence whose values do not exceed 
     * four million, find the sum of the even-valued terms.
  */
    public static void problem2_Algo(){
        int[] tab = new int[1000];
        tab[0]=1;
        tab[1]=2; 
        int fibonacciValue = tab[0] + tab[1];      
        for(int i=2;fibonacciValue<4000000;i++){
            tab[i] = tab[i-2] + tab[i-1];
            if((tab[i]<4000000) && (tab[i]%2 == 0)){
                fibonacciValue += tab[i];
            }
        }
        //Minus one cause we remove tab[0] wich is not even number
        fibonacciValue-=1;
        System.out.println(fibonacciValue);
    }
    /**
     * Problem 3
     * The prime factors of 13195 are 5, 7, 13 and 29.What is the
     * largest prime factor of the number 600851475143 ?
  */
    public static void problem3_Algo(int number){
       //int primeNumber[]={2,3,5,7,11,13,17,19,23,29,31,37,41,43,47,53,59,61,67,71,73,79,83,89,97};
        while (number%2 == 0){
            number/= 2;
            problem3_Algo(number);
        }
        System.out.println(number);
    }
}
